version: 3

tasks:

  clean:
    cmds:
      - rm -rf dist build *.egg-info .venv

  install:
    cmds:
      - uv sync --all-packages

  check:
    cmds:
      - uv run ty check

  build:
    deps: [clean]
    cmds:
      - uv build

  local-deploy:
    deps: [build]
    cmds:
      - uv tool install --python 3.13.9 .

  bump-minor:
    cmds:
      - uv version --bump patch

  publish:
    cmds:
      - uv publish