version: 3

tasks:

  clean:
    cmds:
      - rm -rf dist build *.egg-info .venv

  deps:install:
    cmds:
      - uv sync --all-packages

  build:
    deps: [clean]
    cmds:
      - uv build

  install:local:
    deps: [build]
    cmds:
      - uv tool install --python 3.13.9 .

  bump-minor:
    cmds:
      - uv version --bump patch

  publish:
    cmds:
      - uv publish