version: 3

tasks:

  build:
    cmds:
      - uv build

  install:local:
    deps: [build]
    cmds:
      - uv tool install --python 3.13.9 .

  bump-minor:
    cmds:
      - uv version --bump patch